### ISSUE TITLE
ZAP gets stuck because of spider crash

### ISSUE THREAD

**Issue by shahsparx** [zaproxy/zaproxy#4738]
**Describe the bug**
While scanning a target, ZAP spider crash due to Data cache size limit, because of a throwed exception. 
**To Reproduce**
1. Run Spider 

**Software versions**
 - ZAP: 2.7.0
 - OS: Ubuntu 16.10
 - Java: 1.8.0_91

**Errors from the zap.log file**
2018-06-07 15:29:02,323 [ZAP-daemon] INFO  DaemonBootstrap - ZAP is now listening on localhost:8080
2018-06-07 15:29:31,674 [ZAP-SpiderInitThread-0] INFO  SpiderThread - Starting spidering scan on https://go.wepay.com at Thu Jun 07 15:29:31 IST 2018
2018-06-07 15:29:31,676 [ZAP-SpiderInitThread-0] INFO  Spider - Spider initializing...
2018-06-07 15:29:31,689 [ZAP-SpiderInitThread-0] INFO  Spider - Starting spider...
2018-06-07 15:30:41,672 [HSQLDB Timer @25d250c6] INFO  ENGINE - Checkpoint start
2018-06-07 15:30:41,672 [HSQLDB Timer @25d250c6] INFO  ENGINE - checkpointClose start
2018-06-07 15:30:41,769 [HSQLDB Timer @25d250c6] INFO  ENGINE - checkpointClose synched
2018-06-07 15:30:41,815 [HSQLDB Timer @25d250c6] INFO  ENGINE - checkpointClose script done
2018-06-07 15:30:41,815 [HSQLDB Timer @25d250c6] INFO  ENGINE - dataFileCache commit start
2018-06-07 15:30:41,925 [HSQLDB Timer @25d250c6] INFO  ENGINE - dataFileCache commit end
2018-06-07 15:30:41,942 [HSQLDB Timer @25d250c6] INFO  ENGINE - checkpointClose end
2018-06-07 15:30:41,943 [HSQLDB Timer @25d250c6] INFO  ENGINE - Checkpoint end - txts: 18385
2018-06-07 15:30:50,185 [ZAP-SpiderThreadPool-0-thread-2] INFO  ENGINE - dataFileCache CACHE SIZE limit reached
2018-06-07 15:30:50,186 [ZAP-SpiderThreadPool-0-thread-2] ERROR SpiderThread - java.sql.SQLException: Data cache size limit is reached: 10000
org.parosproxy.paros.db.DatabaseException: java.sql.SQLException: Data cache size limit is reached: 10000
	at org.parosproxy.paros.db.paros.ParosTableHistory.write(ParosTableHistory.java:296)
	at org.parosproxy.paros.model.HistoryReference.<init>(HistoryReference.java:359)
	at org.zaproxy.zap.extension.spider.SpiderThread.notifySpiderTaskResult(SpiderThread.java:488)
	at org.zaproxy.zap.spider.Spider.notifyListenersSpiderTaskResult(Spider.java:809)
	at org.zaproxy.zap.spider.SpiderTask.run(SpiderTask.java:241)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.sql.SQLException: Data cache size limit is reached: 10000
	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source)
	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source)
	at org.hsqldb.jdbc.JDBCPreparedStatement.fetchResult(Unknown Source)
	at org.hsqldb.jdbc.JDBCPreparedStatement.executeUpdate(Unknown Source)
	at org.parosproxy.paros.db.paros.ParosTableHistory.write(ParosTableHistory.java:349)
	at org.parosproxy.paros.db.paros.ParosTableHistory.write(ParosTableHistory.java:294)
	... 7 more
Caused by: org.hsqldb.HsqlException: Data cache size limit is reached: 10000
	at org.hsqldb.error.Error.error(Unknown Source)
	at org.hsqldb.error.Error.error(Unknown Source)
	at org.hsqldb.persist.Cache.put(Unknown Source)
	at org.hsqldb.persist.DataFileCache.add(Unknown Source)
	at org.hsqldb.persist.RowStoreAVLDisk.add(Unknown Source)
	at org.hsqldb.persist.RowStoreAVLDisk.getNewCachedObject(Unknown Source)
	at org.hsqldb.Table.insertSingleRow(Unknown Source)
	at org.hsqldb.StatementDML.insertSingleRow(Unknown Source)
	at org.hsqldb.StatementInsert.getResult(Unknown Source)
	at org.hsqldb.StatementDMQL.execute(Unknown Source)
	at org.hsqldb.Session.executeCompiledStatement(Unknown Source)
	at org.hsqldb.Session.execute(Unknown Source)
	... 11 more
2018-06-07 15:30:50,188 [ZAP-SpiderThreadPool-0-thread-2] ERROR ZAP$UncaughtExceptionLogger - Exception in thread "ZAP-SpiderThreadPool-0-thread-2"
java.lang.NullPointerException
	at org.zaproxy.zap.extension.spider.SpiderScan.notifySpiderTaskResult(SpiderScan.java:339)
	at org.zaproxy.zap.spider.Spider.notifyListenersSpiderTaskResult(Spider.java:809)
	at org.zaproxy.zap.spider.SpiderTask.run(SpiderTask.java:241)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
2018-06-07 15:31:52,497 [Thread-8] INFO  Spider - Stopping spidering process by request.
2018-06-07 15:31:52,519 [Thread-8] INFO  SpiderThread - Spider scanning complete: false
2018-06-07 15:31:52,551 [Thread-8] INFO  ENGINE - dataFileCache commit start
2018-06-07 15:31:52,626 [Thread-8] INFO  ENGINE - dataFileCache commit end
2018-06-07 15:31:52,635 [Thread-8] INFO  ENGINE - Database closed
2018-06-07 15:31:52,736 [Thread-8] INFO  CoreAPI - OWASP ZAP 2.7.0 terminated.

**Stack trace**
110090 [ZAP-SpiderThreadPool-0-thread-2] INFO hsqldb.db..ENGINE  - dataFileCache CACHE SIZE limit reached
110091 [ZAP-SpiderThreadPool-0-thread-2] ERROR org.zaproxy.zap.extension.spider.SpiderThread  - java.sql.SQLException: Data cache size limit is reached: 10000
org.parosproxy.paros.db.DatabaseException: java.sql.SQLException: Data cache size limit is reached: 10000
	at org.parosproxy.paros.db.paros.ParosTableHistory.write(ParosTableHistory.java:296)
	at org.parosproxy.paros.model.HistoryReference.<init>(HistoryReference.java:359)
	at org.zaproxy.zap.extension.spider.SpiderThread.notifySpiderTaskResult(SpiderThread.java:488)
	at org.zaproxy.zap.spider.Spider.notifyListenersSpiderTaskResult(Spider.java:809)
	at org.zaproxy.zap.spider.SpiderTask.run(SpiderTask.java:241)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.sql.SQLException: Data cache size limit is reached: 10000
	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source)
	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source)
	at org.hsqldb.jdbc.JDBCPreparedStatement.fetchResult(Unknown Source)
	at org.hsqldb.jdbc.JDBCPreparedStatement.executeUpdate(Unknown Source)
	at org.parosproxy.paros.db.paros.ParosTableHistory.write(ParosTableHistory.java:349)
	at org.parosproxy.paros.db.paros.ParosTableHistory.write(ParosTableHistory.java:294)
	... 7 more
Caused by: org.hsqldb.HsqlException: Data cache size limit is reached: 10000
	at org.hsqldb.error.Error.error(Unknown Source)
	at org.hsqldb.error.Error.error(Unknown Source)
	at org.hsqldb.persist.Cache.put(Unknown Source)
	at org.hsqldb.persist.DataFileCache.add(Unknown Source)
	at org.hsqldb.persist.RowStoreAVLDisk.add(Unknown Source)
	at org.hsqldb.persist.RowStoreAVLDisk.getNewCachedObject(Unknown Source)
	at org.hsqldb.Table.insertSingleRow(Unknown Source)
	at org.hsqldb.StatementDML.insertSingleRow(Unknown Source)
	at org.hsqldb.StatementInsert.getResult(Unknown Source)
	at org.hsqldb.StatementDMQL.execute(Unknown Source)
	at org.hsqldb.Session.executeCompiledStatement(Unknown Source)
	at org.hsqldb.Session.execute(Unknown Source)
	... 11 more
110093 [ZAP-SpiderThreadPool-0-thread-2] ERROR org.zaproxy.zap.ZAP$UncaughtExceptionLogger  - Exception in thread "ZAP-SpiderThreadPool-0-thread-2"
java.lang.NullPointerException
	at org.zaproxy.zap.extension.spider.SpiderScan.notifySpiderTaskResult(SpiderScan.java:339)
	at org.zaproxy.zap.spider.Spider.notifyListenersSpiderTaskResult(Spider.java:809)
	at org.zaproxy.zap.spider.SpiderTask.run(SpiderTask.java:241)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by shahsparx** [comment]
Was running ZAP in daemon mode and spider instructions were passed using Python API

**Comment by thc202** [comment]
The spider being stuck was addressed in #4428, fix included in weekly releases. [1]

[1] https://github.com/zaproxy/zaproxy/wiki/Downloads#zap-weekly

**Comment by shahsparx** [comment]
Thanks for the link. I read that issue. In the fix at https://github.com/zaproxy/zaproxy/pull/4434, I saw the note: '(Note that this does not fix the DB cache issue and related exceptions.)'

The crash log above contains HSQLDB data cache limit exceeded exception. Are you sure the above issue is fixed in that weekly release?

**Comment by thc202** [comment]
I was referring to the spider being stuck, for the cache limit you would have to increase it (as mentioned in the other issue). We are investigating a better solution for that though.
