### ISSUE TITLE
Support > Kubuntu 18.04 > How do I start zap?

### ISSUE THREAD

**Issue by p2635** [zaproxy/zaproxy#5099]
This is a quick question, I installed zap by adding the xUbuntu 18.04 repo from opensuse. I am running Kubuntu 18.04 so I set that all up correctly and I can see that I installed it. When I run owasp-zap in the command line, there's no such command so I am confused.

**Comment by kingthorin** [comment]
`zap` or `zap.sh`

**Comment by p2635** [comment]
Neither work straight from the command line, do I actually have to try to find the directory and then execute it from there? It seems very long winded...

**Comment by thc202** [comment]
@cabelo ping :)

**Comment by cabelo** [comment]
Hi, the zap.sh script is in /usr/share/owasp-zap/zap.sh.

I will create a new package with link in / usr / bin.

Sorry for the discomfort.

**Comment by cabelo** [comment]
@p2635 @kingthorin  or @thc202  

done...

Can someone please test? I do not have Ubuntu on my machine ...

**Comment by p2635** [comment]
Hi @cabelo, thanks for your help... I updated it from the repos but it still doesn't work. If it involves building it from scratch and stuff, I'm afraid I'm not technical enough to test it.

**Comment by cabelo** [comment]
Hi @p2635 
file exists in /usr/bin (with owasp-zap name)?

**Comment by cabelo** [comment]
@p2635 i found this error, fix it.

**Comment by p2635** [comment]
Hi @cabelo, thanks for your help... I updated it from the repos but there is no folder called owasp-zap in usr/bin

**Comment by kingthorin** [comment]
It wouldn't be a folder, it would be the executable.

**Comment by p2635** [comment]
Please give me clear steps, this is what I am doing:
1. Update the repo from opensuse for xUbuntu 18.04
2. ls /usr/bin/o*
3. there is no executable nor is there a folder called owasp-zap there

**Comment by kingthorin** [comment]
Is this the repo you’re using?
http://download.opensuse.org/repositories/home:/cabelo/xUbuntu_18.04

**Comment by kingthorin** [comment]
Hmmm the version has changed so maybe you need to remove it, apt update, then install?

**Comment by p2635** [comment]
@kingthorin that did the trick! @cabelo thank you so much!

**Comment by cabelo** [comment]
Hugs to all

**Comment by kingthorin** [comment]
@p2635 thanks for letting us know.
